### ISSUE TITLE
Show if user payment was not received yet

### ISSUE THREAD

**Issue by xonic** [gnebehay/schoselwette#39]

**Comment by gnebehay** [comment]
Du musst das machen, nen?

**Comment by xonic** [comment]
musst mir aber sagenn wie es im backend geht

**Comment by xonic** [comment]
![unknown](https://user-images.githubusercontent.com/133157/40586082-80393806-61bc-11e8-8f5c-e1e26c436c6a.jpeg)
please fix

**Comment by gnebehay** [comment]
Wann passiert das? Auf schosel.net siehts bei mir eigentlich gut aus.

**Comment by gnebehay** [comment]
done
