### ISSUE TITLE
achievement APIs

### ISSUE THREAD

**Issue by xonic** [gnebehay/schoselwette#41]
- gambler
- national expert
- chief hattrick
- superbet hustler
- secret achievement

for each achievement we need the ranking of all players plus the score/rank of logged in player

![score--mobile](https://user-images.githubusercontent.com/133157/40449327-7a556ffe-5ed8-11e8-9677-7dacfc33b141.png)
![stats--players--mobile](https://user-images.githubusercontent.com/133157/40449335-815b7924-5ed8-11e8-83bd-85e0cc83ad6d.png)

**Comment by xonic** [comment]
Please provide the following data for each user object

```// user object
{
  achievements: {
    gambler: {
      rank: 1,
      score: 372.92
    },
    hustler: {
      rank: 34,
      score: 178.41
    },
    expert: {
      rank: 10,
      score: 84.30
    },
    hattrick: {
      rank: 26,
      score: 79.19
    },
    secret: {
      rank: 1
    },
  }
  // ... along with other attributes
}```

**Comment by gnebehay** [comment]
done
