### ISSUE TITLE
stats API

### ISSUE THREAD

**Issue by xonic** [gnebehay/schoselwette#42]
for teams and matches

![stats--teams--mobile](https://user-images.githubusercontent.com/133157/40449440-bb5127f0-5ed8-11e8-854e-2e793c8e8f56.png)
![stats--matches--mobile](https://user-images.githubusercontent.com/133157/40449446-be97b5e6-5ed8-11e8-8969-d9a695e10995.png)

**Comment by gnebehay** [comment]
we might tackle this next

**Comment by xonic** [comment]
duplicates #19
